name: CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - 'release-*'
    paths:
      - 'luci-app-argon-config/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: '23.05'
            ext: 'ipk'
            version_path: 'releases/23.05.5'
          - name: 'snapshot'
            ext: 'apk'
            version_path: 'snapshots'
    container:
      image: openwrt/sdk:latest
      options: --user root
    env:
      VERSION_PATH: ${{ matrix.version_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download SDK
        working-directory: /builder
        run: |
          find .
          /builder/setup.sh ${{ env.VERSION_PATH }}

      - name: Build package (${{ matrix.name }})
        run: |
          ./.github/workflows/build.sh

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.name }}
          path: |
            /builder/bin/packages/x86_64/base/*argon-config*.${{ matrix.ext }}

      - name: Upload logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.name }}
          path: /builder/bin/logs.tar.xz